# Generated by Django 2.2.5 on 2021-01-02 11:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210102_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
    ]
